[phases.setup]
nixPkgs = ["nodejs_22", "curl", "bun"] 
nixLibs = [] 
aptPkgs = []   

[phases.install]
cmds = ["bun --bun install"]
dependsOn = ["setup"]

[phases.build]
cmds = ["bun --bun run build"]
dependsOn = ["install"]

[start]
cmd = "bun --bun start"

# [nix]
# pkgs = ["nodejs_24", "curl", "bun"]

