[phases.setup]
nixPkgs = ["nodejs_24", "curl"] 
nixLibs = [] 
aptPkgs = []   

[phases.install]
cmds = ["npm run install"]
dependsOn = ["setup"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[start]
cmd = "npm start"

# [nix]
# pkgs = ["nodejs_24", "curl", "bun"]

[variables]
NODE_ENV = "production"
