[phases.setup]
nixPkgs = ["nodejs_24"] 
nixLibs = [] 
aptPkgs = []   

[phases.install]
cmds = ["bun run install"]
dependsOn = ["setup"]

[phases.build]
cmds = ["bun run build"]
dependsOn = ["install"]

[start]
cmd = "bun start"

[nix]
pkgs = ["nodejs_24", "curl", "bun"]

[variables]
NODE_ENV = "production"
